// Questions
var q = [
	'What are you making?',
	'Won’t this just become a dating app?',
	'How are you going to market it?',
	'Why loneliness?',
	'Like what type of marketing?',
	'Surely university is the place for meeting new people / no routine?',
	'If they’re too disinterested in joining societies, then why would they commit to the app?',
	'Are you open to dating?',
	'Are you open to group meetups?',
	'Why instantaneous?',
	'Who needs what you’re making?',
	'How do you know they need it?',
	'What are they doing now?',
	'What, exactly, makes you different from existing options?',
	'How does your product work in more detail?',
	'How many people are in your target market?',
	'Who are your competitors?',
	'Which competition do you fear most?',
	'What are some trends in your target market, and related markets?',
	'Why will you succeed over others?',
	'What are current alternatives?',
	'Why is nobody else doing this?',
	'If your startup succeeds, what additional areas might you be able to expand into?',
	'How do you see your product evolving as you gain users?',
	'How long can you go before funding?',
	'What will you do if we don’t fund you?',
	'Why did your team get together?',
	'How did your team get together?',
	'Who is “the boss”?',
	'How do we know your team will stick together?',
	'Who in your team does what?',
	'Who will be your next hire?',
	'Biggest argument between co founders?',
	'Why did you choose this idea?',
	'Why do you want to dedicate your life to working on this?',
	'Tell us something surprising that has happened.',
	'What’s the biggest mistake you have made?',
	'Are you open to changing your idea?',
	'Isn’t this a bit creepy?',
	'How far along are you?',
	'Who is going to be your first customer?',
	'How much money do you need to do what you want to do?',
	'How will you make money?',
	'What makes new users try you?',
	'How do you get users?',
	'What resistance will users have to trying it out and how will you overcome it?',
	'Six months from now, what’s going to be your biggest problem?',
	'Why university students first?',
	'What would you talk about?',
	'What’s the business model?',
	'How will you retain users: once someone has made a few friends they will no longer need to use the app?',
	'What metric will you measuee to track your growth?',
	'What will you do in 6 months time if no one is using the app?',
	'Is this just for lonely people?',
	'What if people press linkup and then never go to it?',
	'What if people keep not going to linkups?',
	'Why would lonely people be bothered to use this if they aren’t bothered to find friends in other ways?',
	'Is your app not going to be perceived as uncool?',
	'Is targeting lonely people not negative?',
	'Aren’t you the uber for making friends?',
	'How are you going to ensure a quality experience for users?',
	'What if students never find someone they get along with?',
	'How will you match people?',
	'Fair enough London has a lot of cafes. How will this work somewhere like say Durham?',
	'Do you see this working in the US?',
	'How many users can you get in London?',
	'Why meet at cafes?',
	'What if I don’t like coffee?',
	'How can you ensure all cafe’s are actually even worth going?',
	'Why random?',
	'How will the paid users thing work?',
	'How much of a real friendship can you really create from a coffee chat?',
	'So will you always need marketing to maintain users?',
	'Why not start in the US market first?',
	'What stops somebody else making this app in another city?',
	'If you 3 are going to be the first users. Won’t that guarantee that nobody will ever make a real friend?',
	'Are you sure two guys will get along, won’t they just want to find girls?',
	'More specifically, what would this marketing look like?',
	'What if we have an international student who cannot speak English?',
	'How could this grow organically?',
	'Won’t people feel embarrassed telling others that they’ve used this?',
	'You say your app is purely about real-life interaction. So you don’t want people on the app?',
	'International students have their own societies right?',
	'Why such a big reliance on marketing?',
	'How will marketing make or break this idea?',
	'What if 2 users hate each other?',
	'Can 2 people Linkup multiple times?',
	'Who is going to be your first user?',
	'How much money can you really make from cafes?',
	'What if in linkup X?',
	'What if they lock their phone and it measures them as non responsive?',
	'How long are Linkups?',
	'How often do you see this app being used?',
	'What if students become disinterested after a few linkups where they do not get along with somebody?',
	'Won’t students feel uncomfortable meeting a stranger?',
	'What if you have to try again many times?',
	'How many users do you currently have?',
	'Can’t people just meet people online?',
	'Doesn’t everyone want to meet new people?',
	'Can students not just turn up to a society once and meet 5 new people?',
	'Ca you not just talk to someone in lectures?',
	'Can you not just talk to people in accommodation?',
	'Do SUs not host events?',
	'Won’t a user require confidence to meet new people?',
	'Aren’t universities doing something to tackle this?'

];

	

// Tips
var tips = [
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to PG and the other YC partners, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
	'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
	'He talks quickly, and so do the other YC partners. Try to match their tempo (as you should when talking to anyone).'
];
